### ISSUE TITLE
80X branch

### ISSUE THREAD

**Issue by emanueledimarco** [ECALELFS/ECALpro#6]
Hi Shervin,

can you make a 80X branch in the central repository, so we develop it and we leave te other for 74X (ideally what it is in master should go in a 74X branch). Thanks.

**Comment by emanueledimarco** [comment]
Maybe the master can be the 80X, but we need a branch for 2015 calibrations (74X)

**Comment by shervin86** [comment]
80X is a development branch, the branch 74X is now a copy of the master and will stay as it is for future reference.
